src/Entity/ProfessionalExperience.php
<?php

namespace App\Entity;

use App\Repository\ProfessionalExperienceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProfessionalExperienceRepository::class)]
class ProfessionalExperience
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $position = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $company = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(?string $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): static
    {
        $this->company = $company;

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $repository_link = null;

    #[ORM\ManyToMany(targetEntity: Image::class, inversedBy: 'projects', cascade: ['persist'], orphanRemoval: false)]
    private Collection $images;

    #[ORM\ManyToMany(targetEntity: Article::class, mappedBy: 'projects')]
    private Collection $articles;

    #[ORM\ManyToMany(targetEntity: Technology::class, inversedBy: 'projects')]
    private Collection $technologies;

    #[ORM\Column(nullable: true)]
    private ?int $ranking = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->articles = new ArrayCollection();
        $this->technologies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getWebsiteLink(): ?string
    {
        return $this->website_link;
    }

    public function setWebsiteLink(?string $website_link): static
    {
        $this->website_link = $website_link;

        return $this;
    }

    public function getRepositoryLink(): ?string
    {
        return $this->repository_link;
    }

    public function setRepositoryLink(?string $repository_link): static
    {
        $this->repository_link = $repository_link;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImage(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        $this->images->removeElement($image);

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addProject($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            $article->removeProject($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Technology>
     */
    public function getTechnology(): Collection
    {
        return $this->technologies;
    }

    public function addTechnology(Technology $technology): static
    {
        if (!$this->technologies->contains($technology)) {
            $this->technologies->add($technology);
        }

        return $this;
    }

    public function removeTechnology(Technology $technology): static
    {
        $this->technologies->removeElement($technology);

        return $this;
    }

    public function getRanking(): ?int
    {
        return $this->ranking;
    }

    public function setRanking(?int $ranking): static
    {
        $this->ranking = $ranking;

        return $this;
    }
}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Regisseur Lionel
{% endblock %}

{% block body %}
	<div class="intro-container mt-10 flex items-center">
		<div class="intro_text w-1/2">
			<h1 class="text-6xl font-bold m-4">Regisseur Lionel</h1>
			<h2 class="text-2xl m-4">Je suis développeur web backend PHP / Symfony</h2>
		</div>
		<div class="intro_media  w-1/2 flex-col items-center justify-center text-center">
			<div class="flex items-center justify-center">
				<img class="rounded-full" src="https://picsum.photos/500" alt="Photo de profil">
			</div>

			<button class="mt-4 px-4 py-2 text-white rounded-md bg-amber-700 hover:bg-amber-800">
				<link rel="stylesheet" href="#contact">
				Me contacter
			</button>
		</div>
	</div>

	<div class="Presentation-container mt-10">
		<h2 class="text-3xl  mb-4">Présentation</h2>
		<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illo natus blanditiis sequi exercitationem quibusdam repudiandae ea doloribus itaque! Ratione expedita rerum dolor veritatis amet eius consequuntur itaque, commodi optio unde? Harum rerum ea quibusdam sit inventore tenetur repudiandae placeat pariatur vel voluptate cumque voluptatibus, dolor laborum voluptatem obcaecati et dolore, architecto enim amet dolorum similique quis modi velit quam. Maxime, unde optio quas corporis et beatae qui ut natus sint! Facere ad dignissimos minus corporis doloribus rerum totam at autem eum, perferendis neque facilis praesentium? Libero mollitia illum quis minima enim illo repellendus assumenda esse, sequi minus sint, modi debitis.</p>
	</div>
	<div class="competence-container mt-10">
		<h2 class="text-3xl  mb-4" class="text-3xl">Compétences</h2>
		<div class="competences flex">
			{% for technology in technologies %}
				<div class="competence mx-5 flex-col items-center justify-center text-center">
					<div class="competence_image">
						<img class="rounded-full" src="https://picsum.photos/100" alt="">
					</div>
					<div class="competence_title">
						{{technology.name}}
					</div>
				</div>
			{% endfor %}
		</div>
	</div>

	<div class="project-container mt-10">
		<h2 class="text-3xl  mb-4">Projets</h2>
		<div class="projects">
			{% for project in firstThreeProjects %}
				<div class="project max-w-2xl mx-auto">
					<div class="project_name">{{project.name}}</div>
					<div class="project_description">{{project.description}}</div>
					<div class="project_website-link">{{project.websiteLink}}</div>
					<div class="project_repository-link">{{project.repositoryLink}}</div>
				</div>
			{% endfor %}
		</div>
	</div>

	<div class="professionnal_exp-container mt-10">
		<h2 class="text-3xl  mb-4">Experiences professionnels</h2>
		{% for professionalExperience in professionalExperiences %}
			<div class="professionnal_exp">
				<div class="professionnal_exp_position">{{professionalExperience.position}}</div>
				<div class="professionnal_exp_company">{{professionalExperience.company}}</div>
				<div class="professionnal_exp_duration">
					{{professionalExperience.startDate|date('m-Y')}}
					à
					{{professionalExperience.endDate|date('m-Y')}}
				</div>
				<div class="professionnal_exp_description">{{professionalExperience.description}}</div>
			</div>
		{% endfor %}

	</div>

	<div class="education-container mt-10">
		<h2 class="text-3xl  mb-4">Formations</h2>
		{% for education in educations %}
			<div class="education">
				<div class="education_title">{{education.title}}</div>
				<div class="education_year">{{education.year}}</div>
				<div class="education_description">{{education.description}}</div>
			</div>
		{% endfor %}
	</div>

{% endblock %}